### ISSUE TITLE
Legacy icons ever create a new entrace in extension configuration

### ISSUE THREAD

**Issue by bremaya** [andia89/order-icons#17] opened 2023-05-22 17:58 UTC
It is possible that legacy indicators and icons (such as those of Wine) are grouped all at once, because whenever I start another instance of the application, another entry is created in the extension's configuration menu. 
![Captura de tela de 2023-05-22 14-55-12](https://github.com/andia89/order-icons/assets/39398165/0da3dd8b-0dfe-474d-8c33-d0a4c121ab9b)
Thanks again for the excellent work on this extension.
![image](https://github.com/andia89/order-icons/assets/39398165/62f86397-268f-4e3c-9b58-d2272a549f22)

**Comment by andia89** [comment] 2023-10-22 13:20
Don't really manage to recreate this problem. Is that maybe with an older version of gnome-shell-appindicators extension? If not is it a specific app it happens with? If I can recreate it should be very easy to fix

**Comment by redeven** [comment] 2023-11-17 13:39
Definitely a thing that still happens. Using the latest version from [AppIndicator and KStatusNotifierItem Support](https://extensions.gnome.org/extension/615/appindicator-support/) for GNOME 45 and latest version from this extension as well. It continues to heavily pollute the list, plus it's basically impossible to keep those apps ordered long-term because a new line simply gets created and your old ordered ones get buried.

Basically without fixing this, the extension ends up serving me no purpose, as half of my tray icons are legacy ones that do this.

So far, happens with all `appindicator-legacy` apps. Apps I personally use that are affected: Fcitx5, KeePassXC, Trackma, Steam.

![image](https://github.com/andia89/order-icons/assets/18680184/a72efda7-f8a5-4b02-8ce9-cb0d4b53fd75)

Maybe some sort of regex or pattern name matching could help, so that for example `appindicator-legacy:KeePassXC:*` could be ordered at index X?

**Comment by andia89** [comment] 2023-11-17 14:18
Right it is very easy to fix I think, but I need to be able to reproduce it. Can you maybe tell me exactly which version of KeepasXC (appimage, ppa etc...) you have installed?

**Comment by redeven** [comment] 2023-11-17 15:15
Running:
- `keepassxc` `2.7.6-2` from the [Arch repo](https://archlinux.org/packages/extra/x86_64/keepassxc/)
- `fcitx5` `5.1.5-1` from the [Arch repo](https://archlinux.org/packages/extra/x86_64/fcitx5/)
- `trackma` `0.8.6-1` from the [AUR](https://aur.archlinux.org/packages/trackma)

Those seem like the biggest offenders in legacy icon generation from my screenshot?

Possible reproduction steps (things that could re-initialize tray icons) could be any of:
- Toggling the `AppIndicator and KStatusNotifierItem Support` on and off
- Restarting GNOME with <kbd>Alt+F2</kbd>, although GNOME 45 crashes the entire session when doing that
- Restarting the affected applications

**Comment by andia89** [comment] 2023-11-17 15:45
Ok I'm on it. Managed to reproduce

**Comment by andia89** [comment] 2023-11-17 16:26
fixed with 54d4058

**Closed by andia89** 2023-11-17 16:26 UTC
